[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.25.0",
]

[tool.uv]
dev-dependencies = [
    "bump2version>=1.0.1",
    "pytest>=9.0.2",
]
